### ISSUE TITLE
Cannot convert BFAV Pterodactyl

### ISSUE THREAD

**Issue by Inny78** [AnotherPillow/BFAV2CP#3]
I tried to convert the BFAV part of this mod.
https://www.nexusmods.com/stardewvalley/mods/5575

It fails with this error:
Traceback (most recent call last):
  File "D:\Down\Mods\Stardew Valley\BFAV\BFAV2CP\main.py", line 16, in <module>
    conversion = BFAV2CP(logger)
                 ^^^^^^^^^^^^^^^
  File "D:\Down\Mods\Stardew Valley\BFAV\BFAV2CP\src\Converter.py", line 37, in __init__
    shop = animal['AnimalShop']
           ~~~~~~^^^^^^^^^^^^^^
KeyError: 'AnimalShop'

**Comment by AnotherPillow** [comment]
Will add a warning, as I don't want to undermine mods by making them purchasable when not meant to be.
